package constant;

public enum Permit {
    CREATE
    , DELETE
    , READ
    , UPDATE

    , CREATE_COURSE
    , DELETE_COURSE
    , READ_COURSE
    , UPDATE_COURSE
    , REGISTER_COURSE

    , CREATE_EMPLOYEE
    , DELETE_EMPLOYEE
    , READ_EMPLOYEE
    , UPDATE_EMPLOYEE

    , CREATE_PROFESSOR
    , DELETE_PROFESSOR
    , READ_PROFESSOR
    , UPDATE_PROFESSOR
    , ADD_PROFESSOR_COURSES
    , SALARY_PROFESSOR_I

    , CREATE_STUDENT
    , DELETE_STUDENT
    , READ_STUDENT
    , UPDATE_STUDENT
    , GET_STUDENT_I
    , SCORE_STUDENT

}
